apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../namespace.yaml
  - ../../api-deployment.yaml
  - ../../api-service.yaml
  - ../../api-hpa.yaml
  - ../../configmap.yaml
  - ../../secret.yaml
  - ../../ingress.yaml
replicas:
  - name: agr-api
    count: 3
images:
  - name: agr-api
    newTag: ci-generated-tag
