apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agr-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - agr.example.com
      secretName: agr-example-com-tls
  rules:
    - host: agr.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agr-api
                port:
                  number: 80
